config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :players

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :ranking, presence: true, length: {minimum: 1, maximum: 4}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home

  end

  def about

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @player = Player.order("#{sort_column} #{sort_direction}")
  end

  def new
    @player = Player.new
  end

  def create
    #render plain: params[:player].inspect
    @player = Player.new(player_params)
    if @player.save
      flash[:notice] = "Player was successfully added"
      redirect_to players_path(@player)
    else
      render 'new'
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      flash[:notice] = "Player was successfully updated"
      redirect_to player_path(@player)
    else
      render 'edit'
    end
  end

  private
  def player_params
    params.require(:player).permit(:name, :ranking)
  end

  def sortable_columns
    ["name", "ranking"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "ranking"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/players_helper.rb
module PlayersHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scorecard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About Players!</h2>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h2>Hello Players!</h2>

<%= link_to 'About', pages_about_path %>

app/views/player/edit.html.erb
<h2> Edit exiting player</h2>
  <% if @player.errors.any? %>
    <h2>The following errors prevented the player from getting created</h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_for @player do |f| %>
      <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :ranking %><br/>
        <%= f.text_area :ranking %>
      </p>
      <p>
        <%= f.submit %>
      </p>
      <% end %>
      <%= link_to "Back to players listing", players_path %>

app/views/player/new.html.erb
<h1>Create an player</h1>
  <%= form_for @player do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ranking %><br/>
    <%= f.text_area :ranking %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <% if @player.errors.any? %>
  <h2>The following errors prevented the player from getting created</h2>
    <ul>
      <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <%= link_to "Back to players listing", players_path %>

app/views/players/edit.html.erb
<h2> Edit exiting player</h2>
  <% if @player.errors.any? %>
    <h2>The following errors prevented the player from getting created</h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_for @player do |f| %>
      <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :ranking %><br/>
          <%= f.number_field :ranking, max: 100 %>
      </p>
      <p>
        <%= f.submit %>
      </p>
      <% end %>
      <%= link_to "Back to players listing", players_path %>

app/views/players/index.html.erb
<h4>Listing of all Players</h4>
 <p>
   <%= link_to "Create new player", new_player_path %>
 </p>
 <table class="table table-bordered table-striped">
   <thead>
     <tr>
       <th><%= sort_link "name" %></th>
       <th><%= sort_link "ranking" %></th>
     </tr>
    </thead>
      <tbody>
        <% @player.each do |player| %>
         <tr>
           <td><%=  player.name %></td>
           <td><%=  player.ranking %></td>
           <td><%= link_to 'Edit', edit_player_path(player) %></td>
           <td><%= link_to 'Show', player_path(player) %></td>
         </tr>
       <% end %>
     </tbody>
 </table>

app/views/players/new.html.erb
<h1>Create an player</h1>
  <%= form_for @player do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ranking %><br/>
    <%= f.number_field :ranking, max: 100 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <% if @player.errors.any? %>
  <h2>The following errors prevented the player from getting created</h2>
    <ul>
      <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <%= link_to "Back to players listing", players_path %>

app/views/players/show.html.erb
<h1>Showing selected player</h1>
  <p>
    Name: <%= @player.name %>
  </p>
  <p>
    Ranking: <%= @player.ranking %>
  </p>
<%= link_to "Edit this player", edit_player_path(@player) %> |
<%= link_to "Back to players listing", players_path %>